# Generated by Django 2.1.5 on 2022-08-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import voteapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('voteType', models.IntegerField(choices=[(1, 'CATS'), (2, 'DOGS'), (3, 'TIE')], default=voteapp.models.VoteType(3))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
